### ISSUE TITLE
website settings

### ISSUE THREAD

**Issue by sharonlucong** [sharonlucong/acgKnowledge#4]
- [x] 网站名字
- [x]  网站图标
- [x] slogan? slogan bkg would look better if using gifs

**Comment by Zoeee1616** [comment]
## Brainstorm

想起什么就写了哈 不成熟 可讨论

Website Name | Sub Title | Icon | 
------------ | ------------- | -------------
ACG卧游小站  |  足不出户 带你透过一个个ACG作品了解一个个新的领域 - 从爱出发 了解更宽广的世界 | ![2236](https://user-images.githubusercontent.com/10397505/29842932-29f61626-8cbf-11e7-949b-db5f030865cb.gif) | 

p.s. just use a test image for Icon for now

**Comment by sharonlucong** [comment]
知十？（取自闻一知十，表达从一个作品中可以知道很多事？音同`知识`）
一十？ （同上，“一十”激起千层浪，哈哈哈）


一生万物? (一生二，二生三，三生万物)

ref1: 从爱出发想到这个：`知之者不如好知者,好知者不如爱知者` 因为热爱所以求知？ 
ref2: 我喜欢一句话：怕什么真理无穷，进一寸有一寸的欢喜（摘自胡适写的中国社科院社歌。。）

喜欢`从爱出发`这个口号

**Comment by Zoeee1616** [comment]
喜欢 知十 !!! 
但是有点感觉像文学版的知乎 有点不太ACG　不过我们也可以做的正经一点 :)　
喜欢胡适那句话的洒脱 
网站风格突然变得好像文人的客栈 哈哈哈

p.s. 感觉应该先写个About 找找定位和风格 试着写了一下 可能风格略软弱了..  

知十

About Zhishi: 这是一个ACG爱好者们集结的网站 感谢你找到知十 相信你也和我们一样  被某一部ACG作品激发了求知欲 希望了解更多关于作品里涉猎到的另一个领域的知识 在这里 我们跟你一起从爱出发 分享知识 丰富自己 做有品质的ACG爱好者

About us:

**Comment by sharonlucong** [comment]
那就先暂定知十了！比较general，可扩展性强😬
about us那块我就先按照你这个提案来了！

**Comment by Zoeee1616** [comment]
哈哈好!!! 知十 :heart_eyes::yellow_heart::star2:
好 先填洞 以后更明确主题了可以砍掉重练 哈哈哈 :smirk:

**Comment by sharonlucong** [comment]
关于icon：
![logo](http://img.supfree.net/shufa/c/169163.gif)

草书的`知`，我脚着可以根据这个变形，因为上面挺像`十`的

**Comment by Zoeee1616** [comment]
草书的知很酷 不过越来越像文人墨客的网站了哈哈哈……

赞新Icon！！！

我之前随便画了俩 太难看了 所以没上传 上周有点忙 没来得及参与 只能给你点赞了 哈哈哈 保持进度👍👍👍

下面我打算重做的 太丑了 还没来得及弄

**Comment by Zoeee1616** [comment]
试着把 知 草书 变形了一下 
或许可以作为网页tab上左边的那个icon？ 
可以改颜色和变形

[知草书vector_smoothed_line_draft.ai.zip]
(https://github.com/sharonlucong/acgKnowledge/files/1273802/vector_smoothed_line_draft.ai.zip)

No.1 | No.2 | No.3 |
------------ | ------------- | ------------- | 
![vector_smoothed_darkbg_round](https://user-images.githubusercontent.com/10397505/30013935-58f76216-90fe-11e7-8cff-e62eb5965eea.png) | ![vector_smoothed_darkbg_roundcorner](https://user-images.githubusercontent.com/10397505/30013937-59289ee4-90fe-11e7-9523-c8026ca682c1.png) | ![vector_smoothed_darkbg](https://user-images.githubusercontent.com/10397505/30013936-591467bc-90fe-11e7-8fbe-f4866e1c0efa.png)


加 背景渐变 

No.1 | No.2 | No.3 |
------------ | ------------- | ------------- |
![vector_smoothed_line_draft](https://user-images.githubusercontent.com/10397505/30014440-0842d37a-9101-11e7-8069-43ab6a6dfc3b.png) | ![vector_smoothed_line_draft2](https://user-images.githubusercontent.com/10397505/30014441-086df816-9101-11e7-84c4-5f6016734c67.png) |![vector_smoothed_line_draft_gradient30](https://user-images.githubusercontent.com/10397505/30014530-9886371a-9101-11e7-852f-0d3f7e783398.png)

**Comment by Zoeee1616** [comment]
嗨。。刚看到你已经做完了
那就用你那个吧 挺好的！！！
